package constants

const (
	MYSQL_DRIVER      = "mysql"
	DATABASE_HOST     = "DATABASE_HOST"
	DATABASE_USER     = "DATABASE_USER"
	DATABASE_PASSWORD = "DATABASE_PASSWORD"
	DATABASE_NAME     = "DATABASE_NAME"
	API_PORT          = "API_PORT"
	DEFAULT_API_PORT  = 9000
)
